load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

kernel_module(
    name = "adla",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
        ],
    ),
    outs = [
        "adla_core.ko",
    ],
    kernel_build = select({
        "//common:common_drivers_on_top_dir": "//common_drivers:amlogic",
        "//conditions:default": "//common:amlogic",
    }),
    visibility = ["//visibility:public"],
)

load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_module")
ddk_module(
    name = "adla_ddk",
    srcs = glob(
        [
            "**/*.h",
            "adla/kmd/drv/port/platform/linux/adlak_debugfs.c",
            "adla/kmd/drv/port/platform/linux/adlak_interrupt.c",
            "adla/kmd/drv/port/platform/adlak_hw.c",
            "adla/kmd/drv/port/platform/linux/adlak_io.c",
            "adla/kmd/drv/port/platform/linux/adlak_platform_config.c",
            "adla/kmd/drv/port/platform/linux/adlak_platform_device.c",
            "adla/kmd/drv/port/os/linux/adlak_os.c",
            "adla/kmd/drv/port/os/linux/mm/adlak_mm_os_common.c",
            "adla/kmd/drv/common/mm/adlak_mm_common.c",
            "adla/kmd/drv/common/mm/adlak_mm_smmu.c",
            "adla/kmd/drv/common/mm/adlak_mm_cma.c",
            "adla/kmd/drv/common/mm/adlak_mm_mbd.c",
            "adla/kmd/drv/common/adlak_dpm.c",
            "adla/kmd/drv/common/adlak_queue.c",
            "adla/kmd/drv/common/adlak_context.c",
            "adla/kmd/drv/common/adlak_profile.c",
            "adla/kmd/drv/common/adlak_mm.c",
            "adla/kmd/drv/common/adlak_device.c",
            "adla/kmd/drv/common/adlak_submit.c",
            "adla/kmd/drv/common/adlak_tee.c",
            "adla/kmd/drv/addon/adlak_addon.c",
            "adla/kmd/drv/addon/adlak_platform_addon.c",
        ],
    ),
    hdrs = [
        "//common_drivers:soc_headers",
    ],
    includes = [
        "adla/kmd/drv/port/platform/linux",
        "adla/kmd/drv/port/platform",
        "adla/kmd/drv/port/os/linux/mm",
        "adla/kmd/drv/port/os/linux",
        "adla/kmd/drv/port/os",
        "adla/kmd/drv/port",
        "adla/kmd/drv/uapi/linux",
        "adla/kmd/drv/uapi",
        "adla/kmd/drv/common/mm",
        "adla/kmd/drv/common",
        "adla/kmd/drv/addon",
        "adla/kmd/drv",
    ],
    local_defines = [
        "CONFIG_ADLAK_FIXUP_TIMESTAMP_ENABLE=1",
        "CONFIG_ADLAK_TEE=1",
    ],
    out = "adla_core.ko",
    kernel_build = "//common_drivers:amlogic",
    visibility = ["//visibility:public"],
    deps = [
        "//common_drivers/drivers/gki_tool:amlogic-gkitool",
        "//common_drivers/drivers/cpu_info:amlogic-cpuinfo",
        "//common_drivers/drivers/debug:amlogic-debug",
        "//common_drivers/drivers/tee:amlogic-tee",
        "//common_drivers/drivers/aml_tee:tee",
    ],
)
