load("//build/kernel/kleaf:kernel.bzl", "kernel_module")

kernel_module(
    name = "adla",
    srcs = glob(
        ["**"],
        exclude = [
            "BUILD.bazel",
        ],
    ),
    outs = [
        "adla_core.ko",
    ],
    kernel_build = select({
        "//common:common_drivers_on_top_dir": "//common_drivers:amlogic",
        "//conditions:default": "//common:amlogic",
    }),
    visibility = ["//visibility:public"],
)
